services:

    db:
        image: postgres
        ports:
            - 127.0.0.1:5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: qazxswedc
            POSTGRES_DB: notes

    adminer:
        image: adminer
        ports:
            - 127.0.0.1:8081:8080
